import { FontInterface } from './types';

export const fontList: FontInterface[] = [
  { fontFamily: 'Arial', fontName: 'Arial' },
  { fontFamily: 'Arial Black', fontName: 'Arial Black' },
  { fontFamily: 'Bahnschrift', fontName: 'Bahnschrift' },
  { fontFamily: 'Calibri', fontName: 'Calibri' },
  { fontFamily: 'Cambria', fontName: 'Cambria' },
  { fontFamily: 'Cambria Math', fontName: 'Cambria Math' },
  { fontFamily: 'Candara', fontName: 'Candara' },
  { fontFamily: 'Comic Sans MS', fontName: 'Comic Sans MS' },
  { fontFamily: 'Consolas', fontName: 'Consolas' },
  { fontFamily: 'Constantia', fontName: 'Constantia' },
  { fontFamily: 'Corbel', fontName: 'Corbel' },
  { fontFamily: 'Courier New', fontName: 'Courier New' },
  { fontFamily: 'Ebrima', fontName: 'Ebrima' },
  { fontFamily: 'Franklin Gothic Medium', fontName: 'Franklin Gothic Medium' },
  { fontFamily: 'Gabriola', fontName: 'Gabriola' },
  { fontFamily: 'Gadugi', fontName: 'Gadugi' },
  { fontFamily: 'Georgia', fontName: 'Georgia' },
  { fontFamily: 'HoloLens MDL2 Assets', fontName: 'HoloLens MDL2 Assets' },
  { fontFamily: 'Impact', fontName: 'Impact' },
  { fontFamily: 'Ink Free', fontName: 'Ink Free' },
  { fontFamily: 'Javanese Text', fontName: 'Javanese Text' },
  { fontFamily: 'Leelawadee UI', fontName: 'Leelawadee UI' },
  { fontFamily: 'Lucida Console', fontName: 'Lucida Console' },
  { fontFamily: 'Lucida Sans Unicode', fontName: 'Lucida Sans Unicode' },
  { fontFamily: 'Malgun Gothic', fontName: 'Malgun Gothic' },
  { fontFamily: 'Marlett', fontName: 'Marlett' },
  { fontFamily: 'Microsoft Himalaya', fontName: 'Microsoft Himalaya' },
  { fontFamily: 'Microsoft JhengHei', fontName: 'Microsoft JhengHei' },
  { fontFamily: 'Microsoft New Tai Lue', fontName: 'Microsoft New Tai Lue' },
  { fontFamily: 'Microsoft PhagsPa', fontName: 'Microsoft PhagsPa' },
  { fontFamily: 'Microsoft Sans Serif', fontName: 'Microsoft Sans Serif' },
  { fontFamily: 'Microsoft Tai Le', fontName: 'Microsoft Tai Le' },
  { fontFamily: 'Microsoft YaHei', fontName: 'Microsoft YaHei' },
  { fontFamily: 'Microsoft Yi Baiti', fontName: 'Microsoft Yi Baiti' },
  { fontFamily: 'MingLiU-ExtB', fontName: 'MingLiU-ExtB' },
  { fontFamily: 'Mongolian Baiti', fontName: 'Mongolian Baiti' },
  { fontFamily: 'MS Gothic', fontName: 'MS Gothic' },
  { fontFamily: 'MV Boli', fontName: 'MV Boli' },
  { fontFamily: 'Myanmar Text', fontName: 'Myanmar Text' },
  { fontFamily: 'Nirmala UI', fontName: 'Nirmala UI' },
  { fontFamily: 'Palatino Linotype', fontName: 'Palatino Linotype' },
  { fontFamily: 'Segoe MDL2 Assets', fontName: 'Segoe MDL2 Assets' },
  { fontFamily: 'Segoe Print', fontName: 'Segoe Print' },
  { fontFamily: 'Segoe Script', fontName: 'Segoe Script' },
  { fontFamily: 'Segoe UI', fontName: 'Segoe UI' },
  { fontFamily: 'Segoe UI Historic', fontName: 'Segoe UI Historic' },
  { fontFamily: 'Segoe UI Emoji', fontName: 'Segoe UI Emoji' },
  { fontFamily: 'Segoe UI Symbol', fontName: 'Segoe UI Symbol' },
  { fontFamily: 'SimSun', fontName: 'SimSun' },
  { fontFamily: 'Sitka', fontName: 'Sitka' },
  { fontFamily: 'Sylfaen', fontName: 'Sylfaen' },
  { fontFamily: 'Symbol', fontName: 'Symbol' },
  { fontFamily: 'Tahoma', fontName: 'Tahoma' },
  { fontFamily: 'Times New Roman', fontName: 'Times New Roman' },
  { fontFamily: 'Trebuchet MS', fontName: 'Trebuchet MS' },
  { fontFamily: 'Verdana', fontName: 'Verdana' },
  { fontFamily: 'Webdings', fontName: 'Webdings' },
  { fontFamily: 'Wingdings', fontName: 'Wingdings' },
  { fontFamily: 'Yu Gothic', fontName: 'Yu Gothic' },
];
